server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    include-exception: false
spring:
  application:
    name: "Franquicia"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:mysql://localhost:3306/franchise"
    username: "root"
    password: "root"
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
  sql:
    init:
      mode: "always"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
resilience4j:
  circuitbreaker:
    instances:
      franchiseCreate:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        ignore-exceptions:
          - co.com.gestorfranquicia.model.exception.BusinessException
      branchCreate:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        ignore-exceptions:
          - co.com.gestorfranquicia.model.exception.BusinessException
      productCreate:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        ignore-exceptions:
          - co.com.gestorfranquicia.model.exception.BusinessException
      productDelete:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        ignore-exceptions:
          - co.com.gestorfranquicia.model.exception.BusinessException
      productStockUpdate:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        ignore-exceptions:
          - co.com.gestorfranquicia.model.exception.BusinessException
